=== GhastNier/inf2050-a22-projet-equipe19-main/src/main/java/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "numero_de_permis": {
      "type": "string"
    },
    "ordre": {
      "type": "string"
    },
    "cycle": {
      "type": "string"
    },
    "nom" : {
      "type" : "string"
    },
    "prenom" : {
      "type" : "string"
    },
    "sexe" : {
      "type" : "number"
    },
    "heures_transferees_du_cycle_precedent": {
      "type": "number"
    },
    "activites": {
      "type": "array",
      "prefixItems": [
        {
          "type": "object",
          "properties": {
            "description": {
              "type": "string"
            },
            "categorie": {
              "type": "string"
            },
            "heures": {
              "type": "number"
            },
            "date": {
              "type": "string"
            }
          }
        }
      ],
      "minItems": 1
    }
  },
  "required": [
    "numero_de_permis",
    "ordre",
    "cycle",
    "heures_transferees_du_cycle_precedent",
    "activites",
    "nom",
    "prenom",
    "sexe"
  ]
}

=== GhastNier/inf2050-a22-projet-equipe19-main/src/main/java/input_nomPrenomSexe_Invalide.json
{
  "numero_de_permis": "A0001",
  "nom" : "as1t",
  "prenom":"bv5",
  "sexe": 4,
  "ordre": "architectes",
  "cycle": "2021-2023",
  "heures_transferees_du_cycle_precedent": 12,
  "activites": [
    {
      "description": "Cours sur la d√©ontologie",
      "categorie": "cours",
      "heures": 5,
      "date": "2022-01-07"
    }
  ]
}

=== GhastNier/inf2050-a22-projet-equipe19-main/src/main/java/input_nomPrenomSexe_Valide.json
{
  "numero_de_permis": "T0001",
  "nom" : "asdfg",
  "prenom":"zxcv",
  "sexe": 2,
  "ordre": "architectes",
  "cycle": "2021-2023",
  "heures_transferees_du_cycle_precedent": 7,
  "activites": [
    {
      "description": "Cours sur la d√©ontologie",
      "categorie": "cours",
      "heures": 5,
      "date": "2022-01-07"
    }
  ]
}

=== GhastNier/inf2050-a22-projet-equipe19-main/src/main/java/input_numPermis_ordre.json
{
  "numero_de_permis": "AZ9112",
  "nom" : "asdfg",
  "prenom":"zxcv",
  "sexe": 2,
  "ordre": "géologues",
  "cycle": "2019-2022",
  "heures_transferees_du_cycle_precedent": 7,
  "activites": [
    {
      "description": "Cours sur la déontologie",
      "categorie": "cours",
      "heures": 5,
      "date": "2022-01-07"
    }
  ]
}

=== GhastNier/inf2050-a22-projet-equipe19-main/src/main/java/input_Podiatres_Invalide.json
{
  "numero_de_permis": "90001",
  "nom" : "asdfg",
  "prenom":"zxcv",
  "sexe": 2,
  "ordre": "podiatres",
  "cycle": "2019-2022",
  "heures_transferees_du_cycle_precedent": 7,
  "activites": [
    {
      "description": "asdfghjklqwertyuioopzxcvbnm",
      "categorie": "cours",
      "heures": 23,
      "date": "2020-01-07"
    },
    {
      "description": "AAASSSDDDFFFqwertyuiopasdfg",
      "categorie": "atelier",
      "heures": 23,
      "date": "2019-07-07"
    }

  ]
}
